catalogMode: prefer
cleanupUnusedCatalogs: true

publicHoistPattern:
  - "*@rbxts*"

shellEmulator: true

catalogs:
  cli:
    bumpp: ^10.4.1
  dev:
    "@antfu/ni": ^28.2.0
    "@rbxts/compiler-types": ^3.0.0-types.0
    "@rbxts/luau-polyfill": ^1.1.3
    "@rbxts/types": ^1.0.906
    roblox-ts: ^3.0.0
  lint:
    "@isentinel/eslint-config": ^5.0.0-beta.5
    eslint: ^9.39.2
    eslint-plugin-pnpm: ^1.5.0
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
  prod:
    type-fest: ^5.4.4
  script:
    jiti: ^2.6.1
  test:
    "@rbxts/jest-globals": ^3.13.3-ts.1
  tsc:
    "@isentinel/tsconfig": ^1.2.0
    typescript: ^5.9.3

onlyBuiltDependencies:
  - simple-git-hooks
  - unrs-resolver
